# Generated by Django 4.0.2 on 2022-06-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_vestido_cliente_vestido_fecha_reservada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestido',
            name='fecha_reservada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
