# Generated by Django 4.0.4 on 2022-09-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_vestido_fecha_reservada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='12345678-9', help_text='RUT sin puntos, con guión y con digito verificador', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='vestido',
            name='reservado',
            field=models.CharField(blank=True, choices=[('Reservado', 'Reservado'), ('No reservado', 'No reservado')], default='No reservado', help_text='Estado de la reserva', max_length=15),
        ),
    ]
