# Generated by Django 4.0.4 on 2022-09-19 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_arriendo_creado_alter_arriendo_modificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='modificado',
            field=models.DateField(auto_now=True),
        ),
    ]
