# Generated by Django 4.0.4 on 2022-09-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_reserva_creado_reserva_modificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestido',
            name='reservado',
            field=models.CharField(blank=True, choices=[('Reservado', 'Reservado'), ('No reservado', '')], default='No reservado', help_text='Estado de la reserva', max_length=15),
        ),
    ]
