# Generated by Django 4.0.4 on 2022-09-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_vestido_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='anticipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='fecha_anticipo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='fecha_saldo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
