# Generated by Django 4.0.4 on 2022-09-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_arriendo_anticipo_arriendo_fecha_anticipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
