# Generated by Django 4.0.4 on 2022-09-21 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_cliente_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_a_devolver',
            field=models.DateField(blank=True, help_text='Fecha que debe devolver el vestido: Formato dd/mm/aaaa', null=True),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha inicio del arriendo: Formato dd/mm/aaaa', null=True),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='fecha_que_devolvio',
            field=models.DateField(blank=True, help_text='Fecha que devolvió el vestido: Formato dd/mm/aaaa', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='12345678-9', help_text='RUT sin puntos, con guión y digito verificador', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reservada',
            field=models.DateField(help_text='Formato: dd/mm/aaaa'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sku',
            field=models.ForeignKey(help_text='Seleccione el Sku del vestido que reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.vestido'),
        ),
    ]
